// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnRNrnWwpY_lOOv7TV-_EloxQ7_RIh-fE',
    appId: '1:991504632952:web:460c5587830ec97b7ef18d',
    messagingSenderId: '991504632952',
    projectId: 'authcui',
    authDomain: 'authcui.firebaseapp.com',
    storageBucket: 'authcui.firebasestorage.app',
    measurementId: 'G-LC5N3Z4Z5Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgn2BCclKgQJ9u8pEleXK-Q2xeXuQSdKk',
    appId: '1:991504632952:android:a5580afd7c0419527ef18d',
    messagingSenderId: '991504632952',
    projectId: 'authcui',
    storageBucket: 'authcui.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsqrVKTjnc2k-hQsk4TNMdIy3ylhXXohg',
    appId: '1:991504632952:ios:f7f0441fa105ba737ef18d',
    messagingSenderId: '991504632952',
    projectId: 'authcui',
    storageBucket: 'authcui.firebasestorage.app',
    iosBundleId: 'com.example.semesterProject',
  );
}
